### ISSUE TITLE
vroom syntax file disables spellchecking for test comments

### ISSUE THREAD

**Issue by malcolmr** [google/vim-ft-vroom#4]
Comments in a Vroom test aren't in any syntax group, so spellchecking is based upon whether any `@Spell` clusters exist: if some do, the default is that spellchecking of toplevel text is opt-in; otherwise, it's opt-out (see `:help :syn-spell`).

`syntax/vroom.vim` includes `syntax/vim.vim`, which at least in Vim 7.4 includes some `@Spell` clusters, and so spellchecking is disabled (unless you run `:syntax spell toplevel` manually).

Note that simply adding `:syntax spell toplevel` might fix this, but isn't ideal either: it's a global setting, so someone including vroom.vim may not want this. (This causes a problem with the fenced code blocks option in markdown.vim, for example, which can include java.vim, which runs `:syntax spell default` explicitly.)

**Comment by dbarnett** [comment]
I also wanted long vroom prose lines to wrap as comments (I usually have `formatoptions=crql`). I suggested making them comments in the past (which I think might automatically get them spell checking?), but Nate was against it.
